name: Cpanel
description: Create Certificate SSL in use apache and outhers
inputs:
  token:
    description: zerossl.com api access key
    required: true
  user:
    description: hash of the certificate for validation 
    required: true
  zone:
    description: 'If your selected verification method is email verification, use this parameter to specify one or multiple comma-seperated verification email addresses. You need to specify one verification email address per domain.'
    required: true
  name:
    required: true
  value:
    required: true
  ttl:
    required: true
runs:
  using: node16
  main: ./checkDNS.js
branding:
  icon: unlock
  color: gray-dark